name: Keep Replit Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual run

jobs:
  ping-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit URL
        run: curl -s https://arefks.mensaspy.repl.co > /dev/null
